#!/bin/bash
if [ "$#" -eq 0 ]
then
    echo "Usage: ./make file [ \"libs (.maco)\" ]"
    exit 1
fi

./macas $1.macal
echo "Compiled. Saved object file to $1.maco"
./maclk $1.mac $1.maco $2
echo "Ended linking. Run with ./macsim $1.mac"
echo "Cleaning up..."
rm $1.maco
echo "Erased $1.maco"
